package com.hungerfool.demo.controller;


import java.util.concurrent.atomic.AtomicLong;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import com.hungerfool.demo.domain.User;
import com.hungerfool.demo.domain.UserRepository;


@RestController    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;
	
	private final AtomicLong counter = new AtomicLong();

	@RequestMapping("/get")
	public User getP(String name) {
		User person = userRepository.findByName(name).get(0);
		return person;
	}
	
	@RequestMapping("/save")
	public User createPerson(String name) {
		User person = new User();
		person.setName("HungerFool" + counter.incrementAndGet());
		userRepository.save(person);
		return person;
	}

	@RequestMapping("/")
	public String index() {
		return "Hello Spring Boot";
	}
	@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewUser (@RequestParam String name
			, @RequestParam String email) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		User n = new User();
		n.setName(name);
		n.setEmail(email);
		userRepository.save(n);
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<User> getAllUsers() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}
}
